### ISSUE TITLE
Importing error

### ISSUE THREAD

**Issue by JunYongJeong** [tbjohns/BlitzL1#4]
I have the following error on importing blitzl1.
I am using Ubuntu 16.04.3 + Anaconda3 + python3.6

>>> import blitzl1
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/pasta/anaconda3/envs/FM/lib/python3.6/site-packages/blitzl1/__init__.py", line 1, in <module>
    from _blitzl1 import LassoProblem
ModuleNotFoundError: No module named '_blitzl1'

**Comment by tbjohns** [comment]
Hi @JunYongJeong, I haven't tested this library with Anaconda3.  Please try out my newer BlitzML library at https://github.com/tbjohns/BlitzML, and I'll help you there if you have the same issue.  BlitzML is faster and more stable than BlitzL1.
